const API_NULLIFY_ERROR = 'API_NULLIFY_ERROR';
const API_ACTION_COMPLETE = 'API_ACTION_COMPLETE';

const API_PRODUCT_LOADING_START = 'API_PRODUCT_LOADING_START';
const API_PRODUCT_LOADING_SUCCESS = 'API_PRODUCT_LOADING_SUCCESS';
const API_PRODUCT_LOADING_ERROR = 'API_PRODUCT_LOADING_ERROR';
const API_PRODUCT_GET_PRODUCTS = 'API_PRODUCT_GET_PRODUCTS';
const API_PRODUCT_GET_CATEGORIES = 'API_PRODUCT_GET_CATEGORIES';

const API_SALE_LOADING_START = 'API_SALE_LOADING_START';
const API_SALE_LOADING_SUCCESS = 'API_SALE_LOADING_SUCCESS';
const API_SALE_LOADING_ERROR = 'API_SALE_LOADING_ERROR';
const API_SALE_GET_SALES = 'API_SALE_GET_SALES';

const API_CUSTOMER_LOADING_START = 'API_CUSTOMER_LOADING_START';
const API_CUSTOMER_LOADING_SUCCESS = 'API_CUSTOMER_LOADING_SUCCESS';
const API_CUSTOMER_LOADING_ERROR = 'API_CUSTOMER_LOADING_ERROR';
const API_CUSTOMER_GET_CUSTOMERS = 'API_CUSTOMER_GET_CUSTOMERS';

export {
  API_NULLIFY_ERROR,
  API_ACTION_COMPLETE,
  API_PRODUCT_LOADING_ERROR,
  API_PRODUCT_LOADING_START,
  API_PRODUCT_LOADING_SUCCESS,
  API_PRODUCT_GET_PRODUCTS,
  API_PRODUCT_GET_CATEGORIES,
  API_SALE_LOADING_ERROR,
  API_SALE_LOADING_START,
  API_SALE_LOADING_SUCCESS,
  API_SALE_GET_SALES,
  API_CUSTOMER_GET_CUSTOMERS,
  API_CUSTOMER_LOADING_ERROR,
  API_CUSTOMER_LOADING_START,
  API_CUSTOMER_LOADING_SUCCESS,
};
